### PR TITLE
Add new relic agent

### PR DESCRIPTION
**Pull request by geymed**
# Description
Add and install NewRelic agent

### CODE REVIEW

**Comment by navi-hellen** [comment]
Checking now.

**Review by navi-hellen — CHANGES_REQUESTED** [review]
I see you've committed a license key to Git. Shouldn't do that, security-wise. Please remove the entire property from the config file, we'll add it as an environment variable.

**Comment by geymed** [comment]
@navi-hellen please check again

**Review by navi-hellen — APPROVED** [review]
Looking good! You can merge the PR now.

**Pull request merged**
